#!/bin/bash
set -e -x -u

export GEM_HOME="${HOME}/.gem"
mkdir -p "${GEM_HOME}"

pushd cf-release
  for i in {1..5}; do
    echo "Syncing blobs, attempt $i"
    bosh -n --parallel 10 sync blobs && break
  done

  echo "----- Create dev release"
  version=$(date "+%s")
  bosh --parallel 4 -n create release --version ${version} --with-tarball

  mv dev_releases/cf/*.tgz ../created-cf-release/cf-dev-release-${version}.tgz
popd
