#!/bin/bash

set -e -x -u

version=`cat version/number`

pushd diego-release
  bosh --parallel 4 -n create release --with-tarball --version $version --force

  mv dev_releases/diego/*.tgz ../created-diego-release
popd
