#!/bin/bash
#run_deploy

set -x -e

version=`cat ceph-version/number`
pushd cephfs-bosh-release

bosh -n --parallel 10 create release --version $version --name cephfs --force --with-tarball

mv dev_releases/cephfs/*.tgz ../created-cephfs-bosh-release
popd
