#!/bin/bash
#run_deploy

set -x -e

source $(pwd)/cephfs-bosh-release/scripts/ci/utils.sh
check_param DEPLOYMENT_NAME
check_param BOSH_TARGET
check_param BOSH_USERNAME
check_param BOSH_PASSWORD

sudo apt-get update
sudo apt-get --assume-yes install expect

/usr/bin/expect <<EOD
spawn bosh logout
expect eof

spawn bosh target ${BOSH_TARGET}
expect "Your username:"
send "${BOSH_USERNAME}\n"
expect "password:"
send "${BOSH_PASSWORD}\n"
expect eof

spawn bosh login
expect "Your username:"
send "${BOSH_USERNAME}\n"
expect "password:"
send "${BOSH_PASSWORD}\n"
expect eof
EOD

director_uuid=$(bosh status --uuid)

pushd cephfs-bosh-release
echo "Generating Manifest"

./templates/generate_manifest.sh aws cephfs ${BOSH_TARGET} ${BOSH_USERNAME} ${BOSH_PASSWORD}
echo "Manifest Generated"

/usr/bin/expect <<EOD
spawn bosh logout
expect eof
spawn bosh target ${BOSH_TARGET}
spawn bosh login
expect "Your username:"
send "${BOSH_USERNAME}\n"
expect "password:"
send "${BOSH_PASSWORD}\n"
expect eof

set timeout 300
spawn bosh deployments
spawn bosh releases

set timeout 1500
spawn bosh deploy
expect "(type 'yes' to continue):" { send "yes\n" }
expect {
    "Error" { puts stderr Failed; exit 1 }
    eof
}
EOD
popd
