#!/bin/bash -eu
set -ex

function finish {
  pkill ssh || true
}
trap finish EXIT

pushd vars-store/${BBL_STATE_DIR}
  bbl print-env > set-env.sh 
  source set-env.sh
popd

mkdir releases
cp cephfs-bosh-release-tarball/*.tgz releases/cephfs.tgz

generate_cephfs_vars() {
    cat << EOF > ./cephfs-vars.yml
---
cephfs-keyring: |
`echo ${CEPHFS_KEYRING}|sed 's/^/  /'`
EOF
}

generate_cephfs_vars

bosh \
  -n \
  interpolate cephfs-bosh-release/manifest/cephfs.yml \
  --vars-file=./cephfs-vars.yml \
  > interpolated_manifest.yml

bosh \
  -n \
  -d cf \
  stop cephbroker || true

bosh \
  -n \
  -d cephfs \
  delete-deployment || true

bosh \
  -n \
  -d cephfs \
  deploy interpolated_manifest.yml

bosh \
  -n \
  -d cf \
  start cephbroker || true
