#!/bin/bash
#run_deploy

set -x -e

source $(pwd)/cephfs-bosh-release/scripts/ci/utils.sh
check_param CEPHFS_KEYRING_STUB
check_param DIRECTOR_STUB

pushd cephfs-bosh-release
    echo "Generating Manifest"
    ./templates/generate_manifest.sh aws ../${CEPHFS_KEYRING_STUB} ../${DIRECTOR_STUB}
    echo "Manifest Generated"

    mv cephfs-aws-manifest.yml ../generated-manifest/cephfs-manifest.yml

    echo '============================================'
    cat ../generated-manifest/cephfs-manifest.yml
    echo '============================================'
popd
