#!/bin/bash
#run_deploy

set -x -e

source $(pwd)/cephfs-bosh-release/scripts/ci/utils.sh
check_param CF_MANIFEST
check_param CEPHFS_KEYRING_STUB
check_param DIRECTOR_STUB

echo "Generating Manifest"

cephfs-bosh-release/templates/generate_manifest.sh aws \
    ${CF_MANIFEST} \
    ${CEPHFS_KEYRING_STUB} \
    ${DIRECTOR_STUB}

echo "Manifest Generated"

mv cephfs-aws-manifest.yml generated-manifest/cephfs-manifest.yml

echo '============================================'
cat generated-manifest/cephfs-manifest.yml
echo '============================================'
