#!/bin/bash
# vim: set ft=sh

set -e -x

source $(pwd)/cephfs-bosh-release/scripts/ci/utils.sh
check_param CF_USERNAME
check_param CF_PASSWORD

mkdir -p cf-cli
pushd cf-cli

curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar -zx
./cf api --skip-ssl-validation api.persi.cf-app.com
./cf auth ${CF_USERNAME} ${CF_PASSWORD}
./cf create-org pats-org
./cf create-space -o pats-org pats-space
./cf target -o pats-org -s pats-space

# ./cf delete-service-broker -f cephbroker
# temp=$(./cf service-brokers | grep cephbroker)
# if [ "$temp" != "" ]
#     then
#         exit 1
# fi

./cf create-service-broker cephbroker ${CF_USERNAME} ${CF_PASSWORD} http://cephbroker.persi.cf-app.com:8999
temp=$(./cf service-brokers | grep cephbroker)
if [ "$temp" == "" ]
    then
        exit 1
fi

./cf enable-service-access cephfs -o pats-org

./cf create-service cephfs free mycephfs
temp=$(./cf services | grep mycephfs)
if [ "$temp" == "" ]
    then
        exit 1
fi

#popd
#pushd persi-wordpress
#./cf push --no-start
#popd
#pushd cf-cli
#
#./cf bind persi-wordpress mycephfs
#
#./cf start persi-wordpress


./cf delete-service -f mycephfs
temp=$(./cf services | grep mycephfs)
if [ "$temp" != "" ]
    then
        exit 1
fi

./cf delete-service-broker -f cephbroker
temp=$(./cf service-brokers | grep cephbroker)
echo "temp content"
echo $temp
if [ "$temp" != "" ]
     then
         exit 1
fi

popd
