#!/bin/bash
# vim: set ft=sh

set -e

cd cephfs-bosh-release/

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega

./scripts/run-cephdriver-unit-tests -race
