#!/bin/bash
# vim: set ft=sh

set -e

cd cephfs-bosh-release/

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

./scripts/run-acceptance-tests -race
