#!/bin/bash

set -x -e

### Install ceph-fuse and other junk
sudo apt-get update
sudo apt-get --assume-yes install build-essential expect ruby ruby-dev realpath libxml2-dev libsqlite3-dev libxslt1-dev libpq-dev libmysqlclient-dev zlib1g-dev libfuse2

source bosh-env/set-env.sh
chmod 400 bosh-env/ssh-key

bosh -d cephfs scp --gw-private-key=bosh-env/ssh-key cephfs:/var/vcap/jobs/cephfs/keys/ceph.client.admin.keyring .
bosh -d cephfs scp --gw-private-key=bosh-env/ssh-key cephfs:/etc/ceph/ceph.conf .

export CEPH_KEYRING=`cat ceph.client.admin.keyring`
export CEPH_CLUSTER_IP=`bosh -d cephfs instances|grep cephfs|awk '{print $4}'`

pushd cephfs-bosh-release
    bosh sync-blobs

    echo "Installing ceph-fuse"
    dpkg  --force-confdef -i \
        blobs/cephfuse/ceph-fuse_0.80.11-0ubuntu1.14.04.1_amd64.deb \
        blobs/cephfuse/libboost-system1.54.0_1.54.0-4ubuntu3.1_amd64.deb \
        blobs/cephfuse/libboost-thread1.54.0_1.54.0-4ubuntu3.1_amd64.deb \
        blobs/cephfuse/libnspr4_2%3a4.10.10-0ubuntu0.14.04.1_amd64.deb  \
        blobs/cephfuse/libnss3_2%3a3.21-0ubuntu0.14.04.2_amd64.deb    \
        blobs/cephfuse/libnss3-nssdb_2%3a3.21-0ubuntu0.14.04.2_all.deb
    export PATH=$PATH:/opt/inigo/rootfs/bin/

    export GOROOT=/usr/local/go
    export PATH=$GOROOT/bin:$PATH

    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH

    go get github.com/onsi/ginkgo/ginkgo
    go get github.com/onsi/gomega

    ./scripts/run-driver-cert-tests -race
popd
