#!/bin/bash
#run_test

set -x -e

source $(pwd)/cephfs-bosh-release/scripts/ci/utils.sh
check_param DEPLOYMENT_NAME
check_param BOSH_TARGET
check_param BOSH_USERNAME
check_param BOSH_PASSWORD

### Install ruby and the the bosh cli
rm /var/lib/apt/lists/* -vrf
sudo apt-get update
sudo apt-get --assume-yes install build-essential expect ruby ruby-dev libxml2-dev libsqlite3-dev libxslt1-dev libpq-dev libmysqlclient-dev zlib1g-dev ceph-fuse
gem install bosh_cli --no-ri --no-rdoc

/usr/bin/expect <<EOD
spawn bosh logout
expect eof

spawn bosh target ${BOSH_TARGET}
expect "Your username:"
send "${BOSH_USERNAME}\n"
expect "password:"
send "${BOSH_PASSWORD}\n"
expect eof

spawn bosh login
expect "Your username:"
send "${BOSH_USERNAME}\n"
expect "password:"
send "${BOSH_PASSWORD}\n"
expect eof

set timeout 1500
spawn bosh delete deployment ${DEPLOYMENT_NAME}
expect  "(type 'yes' to continue):" { send "yes\n" }
expect {
    "Error" { puts stderr Failed; exit 1 }
    "Skipped" { puts "Skipped"; exp_continue }
    eof
}
EOD
