#!/bin/bash
# vim: set ft=sh

set -e

source $(pwd)/cephfs-bosh-release/scripts/ci/utils.sh
check_param AWS_DEFAULT_REGION
check_param AWS_ACCESS_KEY_ID
check_param AWS_SECRET_ACCESS_KEY

curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

broker_ip=$(aws ec2 describe-instances --filter Name=tag:Name,Values=cephfs/0 --query 'Reservations[0].Instances[0].NetworkInterfaces[0].Association.PublicIp')
temp="${broker_ip%\"}"
temp="${temp#\"}"
broker_ip="$temp"
echo $broker_ip

mkdir -p cf-cli
pushd cf-cli

curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar -zx

./cf login --skip-ssl-validation -a api.persi.cf-app.com -u admin -p burrito

./cf create-service-broker cephfs admin admin http://${broker_ip}:8999

temp=$(./cf service-brokers | grep cephfs)
if [ "$temp" == "" ]
    then
        exit 1
fi

./cf delete-service-broker -f cephfs

popd
