#!/bin/bash
#run_test

set -x -e

tearDown () {
	rm -rf ~/mycephfs/test-dir
	rm -f ~/mycephfs/test.txt
} 

### Install ruby and the the bosh cli
sudo apt-get update
sudo apt-get --assume-yes install build-essential expect ruby ruby-dev libxml2-dev libsqlite3-dev libxslt1-dev libpq-dev libmysqlclient-dev zlib1g-dev ceph-fuse

eval `ssh-agent -s`
chmod 600 deployments-persi/persi-ci/deployments/bosh-director/v1/keys/persi-bosh.pem
ssh-add deployments-persi/persi-ci/deployments/bosh-director/v1/keys/persi-bosh.pem

scp -o StrictHostKeyChecking=no vcap@cephfs.persi.cf-app.com:/var/vcap/jobs/cephfs/keys/ceph.client.admin.keyring .
scp -o StrictHostKeyChecking=no vcap@cephfs.persi.cf-app.com:/etc/ceph/ceph.conf .

sudo mkdir ~/mycephfs
sudo ceph-fuse -k ceph.client.admin.keyring -m cephfs.persi.cf-app.com:6789 ~/mycephfs

pushd ~/mycephfs
    tearDown
    sudo mkdir test-dir
    dir_created=$(ls -d */ | grep test-dir)
    if [ "$dir_created" != "test-dir/" ]
      then
        tearDown
        exit 1
    fi

    sudo sh -c "echo 'some text' > test.txt"
    file_created=$(cat test.txt)
    if [ "$file_created" != "some text" ]
      then
        tearDown
        exit 1
    fi
popd

sudo umount ~/mycephfs
sudo ceph-fuse -k ceph.client.admin.keyring -m cephfs.persi.cf-app.com:6789 ~/mycephfs

pushd ~/mycephfs
    dir_created=$(ls -d */ | grep test-dir)
    if [ "$dir_created" != "test-dir/" ]
      then
        tearDown
        exit 1
    fi

    file_created=$(cat test.txt)
    if [ "$file_created" != "some text" ]
      then
        tearDown
        exit 1
    fi
popd

tearDown