#!/bin/bash
#run_deploy

#bosh target https://52.72.95.180:25555
bosh target https://192.168.50.4:25555

bosh deployment cephfs-manifest.yml

bosh -n create release
bosh upload release
bosh -n deploy
