#!/bin/bash

set -x -e

#tearDown () {
#	rm -rf ~/mycephfs/test-dir
#	rm -f ~/mycephfs/test.txt
#} 

source $(pwd)/cephfs-bosh-release/scripts/ci/utils.sh
check_param DEPLOYMENT_NAME
check_param BOSH_TARGET
check_param BOSH_USERNAME
check_param BOSH_PASSWORD

### Install ruby and the the bosh cli
sudo apt-get update
sudo apt-get --assume-yes install build-essential expect ruby ruby-dev realpath libxml2-dev libsqlite3-dev libxslt1-dev libpq-dev libmysqlclient-dev zlib1g-dev ceph-fuse
gem install bosh_cli --no-ri --no-rdoc

/usr/bin/expect <<EOD
spawn bosh logout
expect eof

spawn bosh target ${BOSH_TARGET}
expect "Your username:"
send "${BOSH_USERNAME}\n"
expect "password:"
send "${BOSH_PASSWORD}\n"
expect eof

spawn bosh login
expect "Your username:"
send "${BOSH_USERNAME}\n"
expect "password:"
send "${BOSH_PASSWORD}\n"
expect eof
EOD

echo "### Generate cephfs-bosh-release manifest"
wget https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.7/spiff_linux_amd64
sudo chmod +x spiff_linux_amd64
sudo ln -s $(pwd)/spiff_linux_amd64 /usr/bin/spiff

pushd cephfs-bosh-release
echo "Generating Manifest"
ls
./templates/generate_manifest.sh aws cephfs ${BOSH_TARGET} ${BOSH_USERNAME} ${BOSH_PASSWORD}
popd

cephfs_ip=$(bosh vms ${DEPLOYMENT_NAME} | grep 'cephfs/0' | awk '{print $11}')
echo $cephfs_ip

eval `ssh-agent -s`
chmod 600 deployments-runtime/persi-ci/deployments/bosh-director/v1/keys/id-rsa-bosh
ssh-add deployments-runtime/persi-ci/deployments/bosh-director/v1/keys/id-rsa-bosh

scp -o StrictHostKeyChecking=no vcap@$cephfs_ip:/etc/ceph/ceph.client.admin.keyring .
scp -o StrictHostKeyChecking=no vcap@$cephfs_ip:/etc/ceph/ceph.conf .

######################################################################################
#### prepare for acceptance
######################################################################################

export CEPH_KEYRING=`cat ceph.client.admin.keyring`
export CEPH_CLUSTER_IP=$cephfs_ip

pushd cephfs-bosh-release

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega 

./scripts/run-acceptance-tests -race
popd

