#!/bin/bash
# vim: set ft=sh

set -e

curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

export AWS_DEFAULT_REGION=us-east-1
export AWS_ACCESS_KEY_ID=AKIAIWQWG25S7FWMIPGA
export AWS_SECRET_ACCESS_KEY='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'

broker_ip=$(aws ec2 describe-instances --filter Name=tag:Name,Values=cephfs/0 --query 'Reservations[0].Instances[0].NetworkInterfaces[0].Association.PublicIp')
temp="${broker_ip%\"}"
temp="${temp#\"}"
broker_ip="$temp"
echo $broker_ip

mkdir -p cf-cli
pushd cf-cli

curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar -zx

./cf login --skip-ssl-validation -a api.persi.cf-app.com -u admin -p burrito

./cf create-service-broker cephfs admin admin http://${broker_ip}:8999

temp=$(./cf service-brokers | grep cephfs)
if [ "$temp" == "" ]
    then
        exit 1
fi

./cf delete-service-broker -f cephfs

popd
