#!/bin/bash

set -x -e

### Install ruby and the the bosh cli
sudo apt-get update
sudo apt-get --assume-yes install build-essential expect ruby ruby-dev realpath libxml2-dev libsqlite3-dev libxslt1-dev libpq-dev libmysqlclient-dev zlib1g-dev ceph-fuse

eval `ssh-agent -s`
chmod 600 deployments-diego/persi-ci/deployments/bosh-director/v1/keys/id-rsa-bosh
ssh-add deployments-diego/persi-ci/deployments/bosh-director/v1/keys/id-rsa-bosh

scp -o StrictHostKeyChecking=no vcap@cephfs.persi.cf-app.com:/var/vcap/jobs/cephfs/keys/ceph.client.admin.keyring .
scp -o StrictHostKeyChecking=no vcap@cephfs.persi.cf-app.com:/etc/ceph/ceph.conf .

######################################################################################
#### prepare for acceptance
######################################################################################

export CEPH_KEYRING=`cat ceph.client.admin.keyring`
export CEPH_CLUSTER_IP=cephfs.persi.cf-app.com

pushd cephfs-bosh-release
    export GOROOT=/usr/local/go
    export PATH=$GOROOT/bin:$PATH

    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH

    go get github.com/onsi/ginkgo/ginkgo
    go get github.com/onsi/gomega

    ./scripts/run-acceptance-tests -race
popd
