#!/bin/bash
#run_deploy

set -x -e

source $(pwd)/cephfs-bosh-release/scripts/ci/utils.sh
check_param DEPLOYMENT_NAME

### Install ruby and the the bosh cli
sudo apt-get update
sudo apt-get --assume-yes install build-essential expect ruby ruby-dev libxml2-dev libsqlite3-dev libxslt1-dev libpq-dev libmysqlclient-dev zlib1g-dev
gem install bosh_cli --no-ri --no-rdoc

### Get spiff
wget https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.7/spiff_linux_amd64
sudo chmod +x spiff_linux_amd64
sudo ln -s $(pwd)/spiff_linux_amd64 /usr/bin/spiff

/usr/bin/expect <<EOD
spawn bosh logout
expect eof

spawn bosh target https://52.72.95.180:25555
expect "Your username:"
send "admin\n"
expect "password:"
send "admin\n"
expect eof

spawn bosh login
expect "Your username:"
send "admin\n"
expect "password:"
send "admin\n"
expect eof
EOD

pushd cephfs-bosh-release
echo "Generating Manifest"

./templates/generate_manifest.sh aws ${DEPLOYMENT_NAME}
echo "Manifest Generated"
bosh -n create release --force --with-tarball --name ${DEPLOYMENT_NAME}

/usr/bin/expect <<EOD
spawn bosh logout
expect eof

spawn bosh login
expect "Your username:"
send "admin\n"
expect "password:"
send "admin\n"
expect eof

set timeout 300
spawn bosh upload release
expect {
    "Error 30014" { puts "Already uploaded"; exp_continue }
    "Error" { puts stderr Failed; exit 1 }
    eof
}

set timeout 1500
spawn bosh deploy
expect "(type 'yes' to continue):" { send "yes\n" }
expect {
    "Error" { puts stderr Failed; exit 1 }
    eof
}
EOD
popd
