#!/bin/bash
#run_test

set -x -e

### Install ruby and the the bosh cli
sudo apt-get update
sudo apt-get --assume-yes install build-essential expect ruby ruby-dev libxml2-dev libsqlite3-dev libxslt1-dev libpq-dev libmysqlclient-dev zlib1g-dev ceph-fuse
gem install bosh_cli --no-ri --no-rdoc

/usr/bin/expect <<EOD
spawn bosh target https://52.72.95.180:25555
expect "Your username:"
send "admin\n"
expect "password:"
send "admin\n"
expect eof

spawn bosh login
expect "Your username:"
send "admin\n"
expect "password:"
send "admin\n"
expect eof
EOD

echo "### Generate cephfs-bosh-release manifest"
wget https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.7/spiff_linux_amd64
sudo chmod +x spiff_linux_amd64
sudo ln -s $(pwd)/spiff_linux_amd64 /usr/bin/spiff

pushd cephfs-bosh-release
echo "Generating Manifest"
ls
./templates/generate_manifest.sh aws
popd

cephfs_ip=$(bosh vms cephfs-bosh-release | grep 'cephfs/0' | awk '{print $11}')
echo $cephfs_ip

# /usr/bin/expect <<EOD
# spawn bosh target https://52.72.95.180:25555
# expect "Your username:"
# send "admin\n"
# expect "password:"
# send "admin\n"
# expect eof

# spawn bosh login
# expect "Your username:"
# send "admin\n"
# expect "password:"
# send "admin\n"
# expect eof

# spawn bosh scp cephfs/0 --gateway_host 52.72.95.180 --gateway_user vcap --download /etc/ceph/ceph.client.admin.keyring ./
# expect eof
# EOD

eval `ssh-agent -s`
chmod 600 deployments-runtime/persi-ci/keys/bosh.pem
ssh-add deployments-runtime/persi-ci/keys/bosh.pem

ssh -o StrictHostKeyChecking=no -t vcap@$cephfs_ip 'sudo chmod 777 /etc/ceph/ceph.client.admin.keyring'
scp -o StrictHostKeyChecking=no vcap@$cephfs_ip:/etc/ceph/ceph.client.admin.keyring .
scp -o StrictHostKeyChecking=no vcap@$cephfs_ip:/etc/ceph/ceph.conf .

sudo mkdir ~/mycephfs
sudo ceph-fuse -k ceph.client.admin.keyring -m $cephfs_ip:6789 ~/mycephfs

pushd ~/mycephfs
sudo mkdir test-dir
dir_created=$(ls -d */ | grep test-dir)
if [ "$dir_created" != "test-dir/" ]
  then
    exit 1
fi

sudo sh -c "echo 'some text' > test.txt"
file_created=$(cat test.txt)
if [ "$file_created" != "some text" ]
  then
    exit 1
fi
popd
