#!/bin/bash
#run_test

set -x -e

tearDown () {
	rm -rf ~/mycephfs/test-dir
	rm -f ~/mycephfs/test.txt
} 

source $(pwd)/cephfs-bosh-release/scripts/ci/utils.sh
check_param DEPLOYMENT_NAME
check_param BOSH_TARGET
check_param BOSH_USERNAME
check_param BOSH_PASSWORD

### Install ruby and the the bosh cli
sudo apt-get update
sudo apt-get --assume-yes install build-essential expect ruby ruby-dev libxml2-dev libsqlite3-dev libxslt1-dev libpq-dev libmysqlclient-dev zlib1g-dev ceph-fuse
gem install bosh_cli --no-ri --no-rdoc

/usr/bin/expect <<EOD
spawn bosh logout
expect eof

spawn bosh target ${BOSH_TARGET}
expect "Your username:"
send "${BOSH_USERNAME}\n"
expect "password:"
send "${BOSH_PASSWORD}\n"
expect eof

spawn bosh login
expect "Your username:"
send "${BOSH_USERNAME}\n"
expect "password:"
send "${BOSH_PASSWORD}\n"
expect eof
EOD

echo "### Generate cephfs-bosh-release manifest"
wget https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.7/spiff_linux_amd64
sudo chmod +x spiff_linux_amd64
sudo ln -s $(pwd)/spiff_linux_amd64 /usr/bin/spiff

pushd cephfs-bosh-release
echo "Generating Manifest"
ls
./templates/generate_manifest.sh aws cephfs
popd

cephfs_ip=$(bosh vms ${DEPLOYMENT_NAME} | grep 'cephfs/0' | awk '{print $11}')
echo $cephfs_ip


eval `ssh-agent -s`
chmod 600 deployments-runtime/persi-ci/deployments/bosh-director/v1/keys/id-rsa-bosh
ssh-add deployments-runtime/persi-ci/deployments/bosh-director/v1/keys/id-rsa-bosh

scp -o StrictHostKeyChecking=no vcap@${cephfs_ip}:/etc/ceph/ceph.client.admin.keyring .
scp -o StrictHostKeyChecking=no vcap@${cephfs_ip}:/etc/ceph/ceph.conf .

sudo mkdir ~/mycephfs
sudo ceph-fuse -k ceph.client.admin.keyring -m ${cephfs_ip}:6789 ~/mycephfs

pushd ~/mycephfs
tearDown
sudo mkdir test-dir
dir_created=$(ls -d */ | grep test-dir)
if [ "$dir_created" != "test-dir/" ]
  then
    tearDown
    exit 1
fi

sudo sh -c "echo 'some text' > test.txt"
file_created=$(cat test.txt)
if [ "$file_created" != "some text" ]
  then
    tearDown
    exit 1
fi
popd

sudo umount ~/mycephfs
sudo ceph-fuse -k ceph.client.admin.keyring -m ${cephfs_ip}:6789 ~/mycephfs

pushd ~/mycephfs
dir_created=$(ls -d */ | grep test-dir)
if [ "$dir_created" != "test-dir/" ]
  then
    tearDown
    exit 1
fi

file_created=$(cat test.txt)
if [ "$file_created" != "some text" ]
  then
    tearDown
    exit 1
fi
popd

tearDown