name: cephfs
director_uuid:  (( merge ))

releases:
  - name: cephfs
    version: latest

jobs:
  - name: cephfs
    instances: 1
    resource_pool: large
    networks:
    - name: ceph-subnet
      default: [dns, gateway]
    - name: public
      static_ips: [52.3.42.29]
    persistent_disk: 25000 # for consul
    templates:
    - release: cephfs
      name: cephfs
    update:
      serial: true

  - name: cephbroker
    instances: 1
    resource_pool: medium
    networks:
    - name: ceph-subnet
      default: [dns, gateway]
    - name: public
      static_ips: [52.204.240.224]
    persistent_disk: 25000 # for consul
    templates:
    - release: cephfs
      name: cephbroker
    log_level: debug

properties:
  cephfs: (( merge ))
  cephbroker: (( merge ))

networks:
- name: ceph-subnet
  subnets:
  - cloud_properties:
      security_groups:
      - sg-a2945ad9
      subnet: subnet-8c2365d4
    dns:
    - 10.10.0.2
    gateway: 10.10.200.1
    range: 10.10.200.0/24
    reserved:
    - 10.10.200.2 - 10.10.200.9
    static:
    - 10.10.200.10 - 10.10.200.105
  type: manual
- name: public
  type: vip

resource_pools:
  - name: large
    network: ceph-subnet
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m3.large
      availability_zone: us-east-1c

  - name: medium
    network: ceph-subnet
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m3.medium
      availability_zone: us-east-1c

compilation:
  workers: 1
  network: ceph-subnet
  reuse_compilation_vms: true
  cloud_properties:
    availability_zone: us-east-1c
    instance_type: m3.large
    ephemeral_disk:
      size: 10000 # in MB
      type: gp2

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
