#!/usr/bin/env bash
set -e

scripts_path=./$(dirname $0)

fly -t persi execute -c $scripts_path/ci/run_driver_cert.build.yml -i cephfs-bosh-release=/Users/pivotal/workspace/cephfs-bosh-release -i deployments-persi=/Users/pivotal/workspace/deployments-persi --privileged
