#!/bin/bash

set -e

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)

if [ -n "$PACKAGE" ]; then
  ginkgo -r "$@" "./src/${PACKAGE}"
else
  pushd $CEPHFS_RELEASE_DIR/src/code.cloudfoundry.org/cephdriver
    ginkgo -r -keepGoing -trace -randomizeAllSpecs -progress --race "$@"
  popd
fi
