#!/bin/bash

set -e -x

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list -app github.com/cloudfoundry-incubator/cephdriver/cmd/...
  gosub list -app github.com/cloudfoundry-incubator/cephbroker/main/...

  # separate test and binary dependencies
  gosub list -test github.com/cloudfoundry-incubator/cephdriver/...
  gosub list -test github.com/cloudfoundry-incubator/cephbroker/...
} > /tmp/packages

cat /tmp/packages | xargs gosub sync
