#!/bin/bash

set -e

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

function sync_package() {
  bosh_pkg=${1}

  shift

  (
    set -e

    cd packages/${bosh_pkg}

    {
      cat spec | grep -v '# gosub'

      for package in $(gosub list "$@"); do
        repo=$(echo ${2} | cut -f1-3 -d/)
        if [ -d "../../src/${repo}/Godeps/_workspace/src/${package}" ]; then
          package="${repo}/Godeps/_workspace/src/${package}"
        fi
        echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
        if ls ../../src/${package}/*.s >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.s # gosub/g'
        fi
      done
    } > spec.new

    mv spec.new spec
  )
}

sync_package cephdriver       -app github.com/cloudfoundry-incubator/cephdriver/cmd/cephdriver
sync_package acceptance-tests -app github.com/cloudfoundry-incubator/cephdriver/cmd/cephdriver
#sync_package cf-debug-server  -app github.com/cloudfoundry-incubator/cf-debug-server &
#sync_package cf-lager         -app github.com/cloudfoundry-incubator/cf-lager &
#sync_package volman           -app github.com/cloudfoundry-incubator/volman &
#sync_package lager            -app github.com/pivotal-golang/lager &
#sync_package ifrit            -app github.com/tedsuo/ifrit

wait

git diff --name-only packages/*/spec